### ISSUE TITLE
Inconsistent Prediction 

### ISSUE THREAD

**Issue by mru4913** [zaki1003/YOLO-CROWD#1]
```Shell
image 3/3 /YOLO-CROWD/../p2pnet/crowd_counting/test3.jpg: 
torch.Size([1, 3, 304, 640]) # resize by yolo code 
```
```
Traceback (most recent call last):
  File "detect.py", line 282, in <module>
    detect()
  File "detect.py", line 103, in detect
    pred = model(img, augment=opt.augment)[0]
  File "/home/casxm/anaconda3/envs/prod_env2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/casxm/albert/YOLO-CROWD/models/yolo.py", line 124, in forward
    return self.forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/casxm/albert/YOLO-CROWD/models/yolo.py", line 140, in forward_once
    x = m(x)  # run
  File "/home/casxm/anaconda3/envs/prod_env2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/xxxx/YOLO-CROWD/models/common.py", line 714, in forward
    return torch.cat(x, self.d)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 20 but got size 19 for tensor number 1 in the list.
```
The error appears when I detect some images from the Internet. So far I haven't located the bug. I'll continue dig into this issue. If you know anything about this, please let me now.

**Comment by Abdulwadood39** [comment]
Did you find any solution for this?

**Comment by newmg** [comment]
# self.stride = int(self.model.stride.max())
        self.stride = max(32,int(self.model.stride.max()))

**Comment by SaneSwan** [comment]
If you are using the pre-trained weights, to solve this problem, in detect.py: replace `stride = int(model.stride.max())` with `stride = max(32,int(model.stride.max()))`
